### ISSUE TITLE
Login Failed during cluster setup for GKE when running on GCP cloud node

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#122]
Deployed the kiosk on a freshly deployed Linux 18.04 LTS VM Instance on GCP.  Installation all went fine, but during the authentication (paste your password from Google into the terminal), I continually got the `Login Failed!` error message.  I tried several iterations with using `sudo`, and do not think that it is related to the issue.

---

Also, and maybe this should be a separate issue, the cluster setup should likely just fail if the authentication step fails. Why allow the user to keep setting up a broken deployment?

**Comment by dylanbannon** [comment]
This doesn't appear to be linked to use of the Google javascript-based ssh terminal.

It seems like the gcloud-login.sh script isn't being executed. Or even found?

**Comment by dylanbannon** [comment]
Alright, firstly, Erik is a bash scripting wizard.

This bug comes from the fact that the `gcloud auth login` command, which is the backbone of the `gcloud-login.sh` script generates extra output, which requires an extra user confirmation step, when being executed from within a Google-owned machine. So, behind the scenes, we thought the command was prompting us for a confirmation code, but it was actually prompting us to type in "Y" first, so when we pasted the confirmation code in the "Y" prompt, we had nothing left to paste in the following prompt, which is where the confirmation code was supposed to go. So, everything would just fail.

The fix was adding the `--quiet` flag to the `gcloud auth login` statement, which suppressed this prompt that only shows up on Google-owned machines, making the command behavior consistent across Google and non-Google machines.
