### ISSUE TITLE
Custom HPA sometime are not able to read scaling metrics.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#187]
Sometimes on starting up a new cluster, the custom HPA values are "unknown".

In order to replicate, I have executed `kubectl get hpa` and we can see the custom resources as `<unknown>/150m`.

In the past, deleting the `prometheus-operator` and redeploying it has worked, though I am not sure what the root cause of this issue is.

**Comment by willgraf** [comment]
It seems like this is a temporary issue on startup.  I will monitor the next few cluster creations, but it may very well be a non-issue.

**Comment by willgraf** [comment]
Prometheus Adapter logs show that it can't read the custom metrics defined in `prometheus-operator`:

```
I0130 23:37:14.751863       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/deepcell/metrics/segmentation_consumer_key_ratio: (3.50791ms) 404 [[kube-controller-manager/v1.14.10 (linux/amd64) kubernetes/bdceba0/system:serviceaccount:kube-system:horizontal-pod-autoscaler] 10.138.0.76:50578]
I0130 23:37:14.761082       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/deepcell/metrics/zip_consumer_key_ratio: (3.198968ms) 404 [[kube-controller-manager/v1.14.10 (linux/amd64) kubernetes/bdceba0/system:serviceaccount:kube-system:horizontal-pod-autoscaler] 10.138.0.76:50578]
I0130 23:37:14.771042       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/deepcell/metrics/tracking_consumer_key_ratio: (3.314698ms) 404 [[kube-controller-manager/v1.14.10 (linux/amd64) kubernetes/bdceba0/system:serviceaccount:kube-system:horizontal-pod-autoscaler] 10.138.0.76:50578]
I0130 23:37:14.801844       1 wrap.go:42] GET /healthz: (121.023µs) 200 [[kube-probe/1.14+] 10.12.2.1:39858]
```

**Comment by willgraf** [comment]
The custom scripts were looking in `redis_script_value`, which apparently should have been `redis_script_values`.

I have no clue how this would "work" sometimes. It seems to me that if it were the wrong variable name, it would be wrong every time, not sometimes.

**Comment by willgraf** [comment]
Related bug: It seems that the version of our `prometheus-adapter` was set to `v0.5.0`, which is actually the appVersion, not the version. This may have caused helm to pull the latest version of the chart, which could have caused the variation in behavior.

**Comment by willgraf** [comment]
Looks like this is not closed after all 😞

**Comment by willgraf** [comment]
I think this may actually be caused by the `avg_over_time` in the scaling formula.  They creat discrete, rather than continuous, data which may be causing issues when trying to fetch the data.

I've redeployed the hpas and monitoring pods several times now and it seems to work each time.

I am not sure what effect this has on our benchmarking results.

**Comment by dylanbannon** [comment]
It turns out that this error (along with a related error, where you can paste a PromQL query into Grafana [say, for example, for formula for our zip_consumer_key_ratio metric:
`                avg_over_time(redis_script_values{key="segmentation_zip_keys"}[15s])
                / on()
                (
                  avg_over_time(kube_deployment_spec_replicas{deployment="zip-consumer"}[15s])
                  +
                  1
                )
`] and get no data back, not even NaN's) are both caused by the `avg_over_time()` call, like Will guessed.

The problem is less with `avg_over_time()` itself and more with how we're using it. I had to learn a little about Prometheus to understand this:

It turns out that, in Prometheus, there is a `scrapeInterval`, which is how often Prometheus scrapes new data from its data sources, and a `evaluationInterval`, which is how often Prometheus sorts through newly-scraped data and makes that data available to the user. From the user's (or HPA's) point of view, scraped data doesn't exist until it's been evaluated. The default values for both of these parameters are `30s` whenever we deploy the `prometheus-operator` Helm chart. This tends to work fine because, for every one scraping of an endpoint, Prometheus runs one evaluation cycle, finds the newly-scraped data point, and updates the metric for users/HPAs/etc.

The problems arise when we decide that we want to take an average of a metric every 15s: `avg_over_time(kube_deployment_spec_replicas{deployment="zip-consumer"}[15s])`. Now, we're effectively overriding the `evaluationInterval` parameter for this one metric. So, we're telling Prometheus, "Scrape a new data point every 30s and compute the average of the newly-scraped data points every 15s." We only scrape one data point every 30s, meaning that every other "tell me what's happened to this metric in the last 15s" demand is going to return nothing - because we haven't observed (read: scraped)  any new data in the last 15s.

Prometheus' conundrum here plays out in (at least) two weird and very poorly documented ways for us:
1) The initial bug in this issue, which is probably a legitimate Prometheus bug that one of us should open. Whenever you do this overly demanding avg_over_time() thing that we're doing, some metrics (e.g., `kube_deployment_spec_replicas`) from this one specific endpoint (`kube-state-metrics`) will stochasticly just not show up in Prometheus. No NAN's, nothing, no record at all. Stochasticly. This was terrible to debug.
2) Sometimes, it gets better than that! Sometimes, even the formulae you use for your custom metrics, like the one I pasted above, won't return any data when input into Prometheus by hand. Again, stochasticly. (It varies by `prometheus-operator` deployment, but never within a given deployment.) This comes from the fact that we have two `avg_over_time()` calls in the formula above, each of which suffers form the 30s-scrape/15s-evaluate issue, meaning every other 15s data point will have to be missing. If you're unlucky enough to have the two calls report their missing data out-of-sync with each other, then you always have one or the other of them reporting a missing data point and your expression evaluates to missing (NaN?) at every time point. I guess Prometheus' way of dealing with this is to show you no data at all.
(Note that these two bugs could appear independently of one another because, even though they share a necessary root cause, they operated through different mechanisms.)

### Solutions
1.
After all that, the simplest solution is to change all of our `15s` to `30s` in our `avg_over_time()` calls. I ran some tests on this and I'm confident it would work. This will likely make the cluster somewhat more stable, in terms of predictability of pod autoscaling, which would be great.

2.
Another, comparably simple, solution that might lead to improved cluster performance (and significantly greater stability!) would be to update Prometheus` default `scrapeInterval` and `evaluationInterval` to `15s`. This requires only two changes: in the `prometheus-operator` Helmfile, we'd change
`values:
  prometheus:
    prometheusSpec:
      scrapeInterval:`
and
`values:
  prometheus:
    prometheusSpec:
      evaluatoinInterval:`
from `“”` to `15s`.
The main caveat with this is that we'd use 2x the storage and CPU on Prometheus. Also, we might need to make similar tweaks to `prometheus-adapter` and our HPAs to see the HPA metrics updating every 15s.

3)
We could leave the default `scrapeInterval`s and `evaluatoinInterval`s where they are and adjust those values on a per-metric basis. It's a little more complicated (I can paste details, if anyone wants them), but it would save on storage and CPU in Prometheus.

**Comment by willgraf** [comment]
@dylanbannon Nice! So to summarize, it sounds like our `evaluatoinInterval` and `scrapeInterval` and `avg_over_time` values must all be the same, either at `30s` (the default) or at `15s`, which we used for our custom metric.  Both seem like simple fixes.

I would be inclined to change the intervals to 15s, but you mentioned:

> This will likely also make the cluster somewhat more stable, in terms of predictability of pod autoscaling

Why is that? I believe we changed the interval to 15s in order to make the HPA a bit more responsive to the current demand.  Expanding that time interval just means our metric reflects the state of the cluster 30s ago rather than 15s ago.

**Comment by willgraf** [comment]
Thanks for the clarification.  I guess we should try both the `15s` and `30s` (once I finish updating/fixing our benchmarking module).  We can compare results for 10k and 100k, and pick the one that's more effective (leaning towards `30s` in case of a tie).
