### ISSUE TITLE
speeding up tf-serving pod creation

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#34]
It would be nice to decrease the initial wait time for predictions.

One possible strategy could be to create a volume as part of the cluster and load the tf-serving docker image onto it during cluster creation. Then, we could just mount the volume onto the GPU instance and save ourselves a minute or two in downloading the tf-serving docker image. Maybe?

Other ideas?

(This issue is not urgent. For now, it's more of a brainstorm. It would be nice to implement solutions for cutting down the initial wait time eventually, though.)

**Comment by dylanbannon** [comment]
I think vanvalenlab/kiosk-redis-consumer#10 and vanvalenlab/kiosk-tf-serving#9, and possibly vanvalenlab/kiosk-tf-serving#7, might help with this.

**Comment by willgraf** [comment]
While there is definitely some wait-time involved in waiting for the pod to create (and hit Ready status), this is due to the size of the official tensorflow serving docker image.  I'm not inclined for us to make our own "lite" version of tf-serving.

Additionally, we also have a script inside the tf-serving container that will read from the bucket and load all models for serving.  This also slows down time until ready, and drastically increases the memory footprint.  Ideally we can know which model to load ahead of time, but for now, the lag in uptime is due to requested features elsewhere.

**Comment by willgraf** [comment]
TF-serving startup is a fixed cost based on the requirements.  There is certainly no way we can speed up the creation on this end, though we've tried to accomodate in #166 by autoscaling intelligently.
