### ISSUE TITLE
creating executable for kiosk

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#82]
@osterman 
@willgraf 
@vanvalen 
If we had an executable, users who know literally nothing about the command line could set up the kiosk. 

Thoughts? Is it possible? Would it be worth the effort?

**Comment by willgraf** [comment]
Circling back to this a year later, I'm not in favor of this. Creating an executable for different operating systems will be a fair amount of work, and docker does this nicely for us.  I believe that giving the commands to copy/paste is sufficient for users with limited command-line experience.

---

Since we have not discussed this issue in a year, I will close this issue.  If we decide to invest the time in making an executable, we can re-open this issue.
